import "./globals.css";
import { Inter } from "next/font/google";
import { ReactQueryClientProvider } from "@/utils/react-query";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { options } from "@/utils/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

const RootLayout = async ({ children }: LayoutProps) => {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
